### ISSUE TITLE
Incorrect Card Stats

### ISSUE THREAD

**Issue by willuwontu** [ParlocameonTheDev/BPP#4]
I made a few pull requests earlier, but that only fixed a few of the issues that your cards have with their stats. 

Cards like [Nuclear](https://github.com/ParlocameonTheDev/BPP/blob/main/Cards/Nuclear.cs) still have the issue of performing math operations in the `SetupCard` function. Some like [MunitionsCase](https://github.com/ParlocameonTheDev/BPP/blob/main/Cards/MunitionsCase.cs) reference the wrong component for their `OnAddCard` (it should be increasing `GunAmmo.reloadTimeAdd`, not `Gun.ReloadTimeAdd` which is used by `ApplyCardStats` to increase `GunAmmo.reloadTimeAdd`), resulting in intended stat changes having no effect. Take the time to view how `ApplyCardStats` applies cards in dnSpy so that these can be properly done.

Additionally, the values for many of the multiplicative stats are wrong, Nuclear's `gun.damage *= 4.00f;` only increases gun damage by 300% instead for 400% for the same reasons that [Red Pill](https://github.com/ParlocameonTheDev/BPP/blob/main/Cards/RedPill.cs)'s `gun.damage = 1.20f;` only increases gun damage by 20%, you need to subtract 1f from their values to get the actual amount changed. For decreased stats you should instead divide 1f by the stat change and then subtract 1f, e.g. `characterStats.health *= 0.5f;` is a stat change of `(1f/0.5f)-1f` for a stat change of `-100% HP`.

**Comment by PenialJackson** [comment]
Thanks for letting me know about these, I haven't worked on C# in years and knew I would mess some things up, I'll look into all of this tomorrow if I have time.
