### ISSUE TITLE
Suggestion: Actual Ground Pound

### ISSUE THREAD

**Issue by SOMSTATE** [ParlocameonTheDev/BPP#7]
If the card dealt damage landing on someone it would make the card a lot more useful, versatile and most importantly fun.

**Comment by SOMSTATE** [comment]
P.S I am a professional animator and artist and would love to help with the card art/animations.

SOM#0001

**Comment by PenialJackson** [comment]
I somehow never really thought of this, but I'm open to this being a thing eventually, would just need to figure out mono behaviors first.

About the card art, we aren't currently in need of any help, but thanks for letting us know :)
